# wrangler.toml
name = 'mini-stock'
compatibility_date = "2025-07-15"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "mini-stock"
database_id = "0e88acb2-be05-4130-8c0d-2022642617d4"
migrations_dir = "migrations"
